### ISSUE TITLE
Special heap keywords in terms

### ISSUE THREAD

**Issue by rec0de** [Edkamb/crowbar-tool#22]
Hi!

I'm having some issues with the `exprToTerm` function when applied to terms that contain `old`.

Looking at the code, I think the conversion is buggy but I'm not sure enough to fix without potentially breaking something. The relevant snippet is below:

https://github.com/Edkamb/crowbar-tool/blob/e9fc52f91fcfbd2e50c319fd0c8af16729b1dc2a/src/main/kotlin/org/abs_models/crowbar/data/LogicElement.kt#L433-L445

- What's the purpose of the `specialHeapKeyword != 'NONE'` comparison? Shouldn't the keyword be updated in any case, maybe giving a warning / exception if the previous keyword was not none?
- Shouldn't the function invocation of `old` be removed in line 442 - similar to how it's done in `exprToForm`?

**Comment by MarcoScaletta** [comment]
The `specialHeapKeyword != 'NONE' comparison` is a residual from the previous implementation and can be refactored by removing lines 435-439.
https://github.com/Edkamb/crowbar-tool/blob/e9fc52f91fcfbd2e50c319fd0c8af16729b1dc2a/src/main/kotlin/org/abs_models/crowbar/data/LogicElement.kt#L433-L445

Line 442 can be safely replaced with `return exprToTerm(input.e[0], input.op)` (the tests will succeed)
Furthermore lines 468-469 can be removed, because complex applications of special keywords are allowed
https://github.com/Edkamb/crowbar-tool/blob/e9fc52f91fcfbd2e50c319fd0c8af16729b1dc2a/src/main/kotlin/org/abs_models/crowbar/data/LogicElement.kt#L466-L476

In any case, are the fields inside `old` and `last` always referred to with the keyword `this.`?
For example, `old(this.field == 0)` instead of `old(field == 0)`.

**Comment by rec0de** [comment]
Great, thank you!
